Parameters:
  ImageUri:
    Type: String
    Description: Enter the full URI of your Lambda container image in Amazon ECR
  ImageBucketName:
    Type: String
    Description: Choose a unique name for the AWS S3 bucket to store your original photos under.

Resources:

  # Lambda function using Docker image
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: AwsLambdaImageResizeExample
      PackageType: Image
      Role: !GetAtt LambdaFunctionRole.Arn
      MemorySize: 1024
      Code:
        ImageUri: 720974690363.dkr.ecr.us-east-1.amazonaws.com/image-resizing:latest

  # IAM Role for Lambda function
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: AppendToLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
      - PolicyName: S3FullAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ImageBucketName
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ImageBucketName
                - '/*'
